version: "3.8"

services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: play_it_cool_dev
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SYSTEM: postgres
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: nette
  # playitcool:
  #   build:
  #     context: ./
  #     args:
  #       DATABASE_URL: ecto://testuser:testpassword@postgres:5432/play_it_cool_dev
  #       SECRET_KEY_BASE: 32t5rg4387rfg387gtg8we
  #       PORT: 4000
  #   environment:
  #     DATABASE_URL: ecto://testuser:testpassword@postgres:5432/play_it_cool_dev
  #     SECRET_KEY_BASE: 32t5rg4387rfg387gtg8we
  #     PORT: 4000
  #     MIX_ENV: prod
  #   working_dir: /app
  #   ports:
  #     - 4000:4000
  #   command: ["bin/play_it_cool", "start"]
