version: "3.7"

services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: testuser 
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: play_it_cool_dev
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SYSTEM: postgres
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: nette